config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    member do
      get :following, :followers
    end
  end
  get 'users/:id' => 'users#show'
  get 'users' => 'users#index'
  get 'buzzwords' => 'buzzwords#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :microposts
  root 'microposts#index'
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buzzword.rb
class Buzzword < ApplicationRecord
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  validates :content, presence: true
  validates :user_id, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    self.following.include?(other_user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :company])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :company])
  end
end

app/controllers/buzzwords_controller.rb
class BuzzwordsController < ApplicationController

  def index
    @buzzwords = Buzzword.all
  end

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorized_user, only: [:edit, :update, :destroy]

  def index
    if current_user.present?
      following_ids_subselect = "SELECT followed_id FROM relationships WHERE  follower_id = #{current_user.id}"
      @microposts = Micropost.where("user_id IN (#{following_ids_subselect}) AND created_at >= :time_range", time_range: 24.hours.ago).order("buzz_count DESC")
    else
      @microposts = Micropost.where('created_at >= ?', 24.hours.ago).order("buzz_count DESC")
    end
  end

  def show
  end

  def new
    @micropost = current_user.microposts.build
  end

  def edit
  end

  def create
    @micropost = current_user.microposts.build(micropost_params.merge("buzz_count": buzzword_count))

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @micropost.update(micropost_params.merge("buzz_count": buzzword_count))
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    def authorized_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to microposts_path, notice: "Not authorized to edit this micropost" if @micropost.nil?
    end

    def micropost_params
      params.require(:micropost).permit(:content, :buzzword_count)
    end

    def buzzword_count
      count = 0
      Buzzword.all.each do |a|
        if micropost_params["content"].downcase.include? a.name
          count += 1
        end
      end
      count
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js {render inline: "location.reload();" }
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js {render inline: "location.reload();" }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/buzzwords/index.html.erb
<% @buzzwords.each do |buzzword| %>
  <%= buzzword.name %>, 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Strings</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header class="navbar navbar-default" role="navigation">
      <div class="navbar-inner">
        <div class="container">
          <div id="logo" class="navbar-brand"><%= link_to "Strings", root_path %></div>
          <nav class="collapse navbar-collapse navbar-ex1-collapse">
          	<% if user_signed_in? -%>
    					<ul class="nav navbar-nav navbar-right">
    						<li><%= link_to 'New Post', new_micropost_path %></li>
                <li><%= link_to 'Users', '/users' %></li>
                <li><%= link_to 'Profile', "/users/#{current_user.id}" %></li>
    						<li><%= link_to 'Account', edit_user_registration_path %></li>
    						<li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
    					</ul>
    				<% else -%>
    					<ul class="nav navbar-nav pull-right">
                <li><%= link_to 'Users', '/users' %></li>
    						<li><%= link_to 'Sign up', new_user_registration_path %></li>
    						<li><%= link_to 'Sign in', new_user_session_path %></li>
    					</ul>
    				<% end -%>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_field :content, class: "form-control" %>
  </div>
  <br>
  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-lg btn-primary" %>
  </div>

<% end %>

app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<% @microposts.each do |micropost| %>
  <div class="micropost row clearfix">
    <h2>
      <%= micropost.content %><br>
      <small class="author">Submitted <%= time_ago_in_words(micropost.created_at) %> ago by <%= link_to micropost.user.name, "/users/#{micropost.user.id}" %></small>
    </h2>
  </div>
<% end %>

app/views/microposts/new.html.erb
<h1>Submit New Micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<div class="page-header">
  <h1><%= @micropost.content %><br> <small>Submitted by <%= @micropost.user.name %></small></h1>
</div>

<% if @micropost.user == current_user -%>
	<div class="btn-group">
		<%= link_to 'Edit', edit_micropost_path(@micropost), class: "btn btn-default" %>
		<%= link_to 'Destroy', @micropost, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
	</div>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless (current_user == @user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-danger" %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= link_to user.name, "/users/#{user.id}" %>
  <br>
<% end %>

app/views/users/show.html.erb
<h2><%= @user.name %> <small>(<%= @user.email %>)</small> </h2>
<%= render 'follow_form' if current_user %>
<h3>Company: <small><%= @user.company %></small></h3>
<h2><%= @user.following.count %> Following</h2>
<h2><%= @user.followers.count %> Followers</h2>
 <br>
<%= @user.microposts.each do |micropost| %>
  <h4><%= micropost.content %><br> <small class="author">Submitted <%= time_ago_in_words(micropost.created_at) %> ago</small></h4>
  <% if micropost.user == current_user -%>
  	<div class="btn-group">
  		<%= link_to 'Edit', edit_micropost_path(micropost), class: "btn btn-success" %>
  		<%= link_to 'Delete', micropost, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  	</div>
  <% end %>
  <br><br>
<% end %>